version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.14.0
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  data01: {}