version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.14.0
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.14.0
    ports:
      - '5601:5601'

  logstash:
    image: logstash:7.14.0
    ports:
      - '5000:5000'
    volumes:
      - type: bind
        source: ./logstash_pipeline/
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./postgresql.jar  
        target: /postgresql.jar
    extra_hosts:
      - "localhost:192.168.1.7"
