version: '3.7'

services:
  logstash:
    image: logstash:7.14.0
    ports:
      - '5000:5000'
    volumes:
      - type: bind
        source: ./logstash_pipeline/
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./postgresql.jar  
        target: /postgresql.jar
    extra_hosts:
      - "localhost:192.168.1.7"